project:
  type: manuscript
  render: 
    - "*.qmd"
    - "!notebooks/qPCR/old_qPCR_import/"

execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  #jats: default
  pdf: default



